name: stockml
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - pandas
  - numpy
  - matplotlib
  - seaborn
  - scikit-learn=1.3.0
  - xgboost
  - tensorflow=2.13.0
  - pytorch
  - torchvision
  - nltk
  - transformers
  - tqdm
  - requests
  - beautifulsoup4
  - plotly
  - pip
  - pip:
    - yfinance==0.2.54
    - multitasking
    - vaderSentiment
    - python-dotenv
    - sentencepiece
    - tokenizers